using Tabsan.EduSphere.Domain.Common;

namespace Tabsan.EduSphere.Domain.Notifications;

/// <summary>
/// Types of notifications that can be dispatched in the system.
/// Stored as string in the database for readability and forward compatibility.
/// </summary>
public enum NotificationType
{
    /// <summary>General informational message.</summary>
    General = 1,

    /// <summary>Assignment created or updated by faculty.</summary>
    Assignment = 2,

    /// <summary>Result published by faculty or admin.</summary>
    Result = 3,

    /// <summary>Low-attendance alert triggered by the background job.</summary>
    AttendanceAlert = 4,

    /// <summary>System-level operational notice (licence expiry, maintenance, etc.).</summary>
    System = 5,

    /// <summary>Announcement from a department or institution admin.</summary>
    Announcement = 6
}

/// <summary>
/// A notification message created by a user or the system.
/// The notification header; actual per-user delivery is tracked by <see cref="NotificationRecipient"/>.
/// Notifications are append-only — they can be marked inactive but never edited or deleted.
/// </summary>
public class Notification : BaseEntity
{
    /// <summary>Short subject line shown in notification lists.</summary>
    public string Title { get; private set; } = default!;

    /// <summary>Full message body. May contain plain text or Markdown.</summary>
    public string Body { get; private set; } = default!;

    /// <summary>Category of the notification; controls icons and filtering.</summary>
    public NotificationType Type { get; private set; }

    /// <summary>
    /// The user who sent this notification.
    /// Null when the notification was generated by the system (e.g. licence check job).
    /// </summary>
    public Guid? SenderUserId { get; private set; }

    /// <summary>True when the notification originates from a background job or system event.</summary>
    public bool IsSystemGenerated { get; private set; }

    /// <summary>
    /// When false the notification is hidden from all dashboards.
    /// Faculty/Admins can deactivate a notification before all recipients read it.
    /// </summary>
    public bool IsActive { get; private set; } = true;

    // ── EF constructor ────────────────────────────────────────────────────────
#pragma warning disable CS8618
    private Notification() { }
#pragma warning restore CS8618

    /// <summary>Creates a user-authored notification (not system-generated).</summary>
    public Notification(string title, string body, NotificationType type, Guid senderUserId)
    {
        if (string.IsNullOrWhiteSpace(title)) throw new ArgumentException("Title is required.", nameof(title));
        if (string.IsNullOrWhiteSpace(body))  throw new ArgumentException("Body is required.", nameof(body));

        Title           = title.Trim();
        Body            = body.Trim();
        Type            = type;
        SenderUserId    = senderUserId;
        IsSystemGenerated = false;
        Touch();
    }

    /// <summary>Creates a system-generated notification (no sender user).</summary>
    public Notification(string title, string body, NotificationType type)
    {
        if (string.IsNullOrWhiteSpace(title)) throw new ArgumentException("Title is required.", nameof(title));
        if (string.IsNullOrWhiteSpace(body))  throw new ArgumentException("Body is required.", nameof(body));

        Title             = title.Trim();
        Body              = body.Trim();
        Type              = type;
        IsSystemGenerated = true;
        Touch();
    }

    // ── Behaviour ─────────────────────────────────────────────────────────────

    /// <summary>
    /// Deactivates the notification so it no longer appears in user dashboards.
    /// Recipients who have already read it retain their read-state.
    /// </summary>
    public void Deactivate()
    {
        IsActive = false;
        Touch();
    }
}
